export * from './schema/answer.js';
export * from './schema/manifest.js';
export * from './schema/matrix.js';
export * from './types/file-op.js';
export * from './ports/template-source.js';
export * from './ports/file-writer.js';
export * from './adapters/disk-file-writer.js';
export * from './adapters/memory-file-writer.js';
export * from './merge.js';
export * from './readme.js';
export * from './docker.js';
export * from './ci.js';
export * from './env-generator.js';
export * from './generate.js';
export const CORE_VERSION = '0.3.2';
