version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: '{{projectName}}-mongo'
    restart: always
    environment:
      MONGO_INITDB_DATABASE: '{{projectName}}'
    ports:
      - '${MONGO_PORT:-27017}:27017'
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', 'db.adminCommand("ping")']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
